server:
  port: 9005

spring:
  application:
    name: service-play

  profiles:
    include: common_dev

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/

  instance:
    instance-id: 游戏服务-9005
    prefer-ip-address: true

info:
  author.name: trevor
  app.name: general
  server.port: ${server.port}
  application.name: ${spring.application.name}



